/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-04-29 14:08:19 UTC)
 * on 2013-04-30 at 06:09:19 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.categoryendpoint;

/**
 * Service definition for Categoryendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CategoryendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Categoryendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://project-directory.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "categoryendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Categoryendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Categoryendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Category collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Categoryendpoint categoryendpoint = new Categoryendpoint(...);}
   *   {@code Categoryendpoint.Category.List request = categoryendpoint.category().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Category category() {
    return new Category();
  }

  /**
   * The "category" collection of methods.
   */
  public class Category {

    /**
     * Create a request for the method "category.children".
     *
     * This request holds the parameters needed by the the categoryendpoint server.  After setting any
     * optional parameters, call the {@link Children#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public Children children() throws java.io.IOException {
      Children result = new Children();
      initialize(result);
      return result;
    }

    public class Children extends CategoryendpointRequest<com.google.api.services.categoryendpoint.model.CollectionResponseExtentsionCategory> {

      private static final String REST_PATH = "category/children";

      /**
       * Create a request for the method "category.children".
       *
       * This request holds the parameters needed by the the categoryendpoint server.  After setting any
       * optional parameters, call the {@link Children#execute()} method to invoke the remote operation.
       * <p> {@link
       * Children#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected Children() {
        super(Categoryendpoint.this, "GET", REST_PATH, null, com.google.api.services.categoryendpoint.model.CollectionResponseExtentsionCategory.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Children setAlt(java.lang.String alt) {
        return (Children) super.setAlt(alt);
      }

      @Override
      public Children setFields(java.lang.String fields) {
        return (Children) super.setFields(fields);
      }

      @Override
      public Children setKey(java.lang.String key) {
        return (Children) super.setKey(key);
      }

      @Override
      public Children setOauthToken(java.lang.String oauthToken) {
        return (Children) super.setOauthToken(oauthToken);
      }

      @Override
      public Children setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Children) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Children setQuotaUser(java.lang.String quotaUser) {
        return (Children) super.setQuotaUser(quotaUser);
      }

      @Override
      public Children setUserIp(java.lang.String userIp) {
        return (Children) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String parentKey;

      /**

       */
      public java.lang.String getParentKey() {
        return parentKey;
      }

      public Children setParentKey(java.lang.String parentKey) {
        this.parentKey = parentKey;
        return this;
      }

      @Override
      public Children set(String parameterName, Object value) {
        return (Children) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the CategoryEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Categoryendpoint categoryendpoint = new Categoryendpoint(...);}
   *   {@code Categoryendpoint.CategoryEndpoint.List request = categoryendpoint.categoryEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public CategoryEndpoint categoryEndpoint() {
    return new CategoryEndpoint();
  }

  /**
   * The "categoryEndpoint" collection of methods.
   */
  public class CategoryEndpoint {

    /**
     * Create a request for the method "categoryEndpoint.getCategory".
     *
     * This request holds the parameters needed by the the categoryendpoint server.  After setting any
     * optional parameters, call the {@link GetCategory#execute()} method to invoke the remote
     * operation.
     *
     * @param id
     * @return the request
     */
    public GetCategory getCategory(java.lang.Long id) throws java.io.IOException {
      GetCategory result = new GetCategory(id);
      initialize(result);
      return result;
    }

    public class GetCategory extends CategoryendpointRequest<com.google.api.services.categoryendpoint.model.Category> {

      private static final String REST_PATH = "category/{id}";

      /**
       * Create a request for the method "categoryEndpoint.getCategory".
       *
       * This request holds the parameters needed by the the categoryendpoint server.  After setting any
       * optional parameters, call the {@link GetCategory#execute()} method to invoke the remote
       * operation. <p> {@link
       * GetCategory#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected GetCategory(java.lang.Long id) {
        super(Categoryendpoint.this, "GET", REST_PATH, null, com.google.api.services.categoryendpoint.model.Category.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetCategory setAlt(java.lang.String alt) {
        return (GetCategory) super.setAlt(alt);
      }

      @Override
      public GetCategory setFields(java.lang.String fields) {
        return (GetCategory) super.setFields(fields);
      }

      @Override
      public GetCategory setKey(java.lang.String key) {
        return (GetCategory) super.setKey(key);
      }

      @Override
      public GetCategory setOauthToken(java.lang.String oauthToken) {
        return (GetCategory) super.setOauthToken(oauthToken);
      }

      @Override
      public GetCategory setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetCategory) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetCategory setQuotaUser(java.lang.String quotaUser) {
        return (GetCategory) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetCategory setUserIp(java.lang.String userIp) {
        return (GetCategory) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public GetCategory setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public GetCategory set(String parameterName, Object value) {
        return (GetCategory) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "categoryEndpoint.insertCategory".
     *
     * This request holds the parameters needed by the the categoryendpoint server.  After setting any
     * optional parameters, call the {@link InsertCategory#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link com.google.api.services.categoryendpoint.model.Category}
     * @return the request
     */
    public InsertCategory insertCategory(com.google.api.services.categoryendpoint.model.Category content) throws java.io.IOException {
      InsertCategory result = new InsertCategory(content);
      initialize(result);
      return result;
    }

    public class InsertCategory extends CategoryendpointRequest<com.google.api.services.categoryendpoint.model.Category> {

      private static final String REST_PATH = "category";

      /**
       * Create a request for the method "categoryEndpoint.insertCategory".
       *
       * This request holds the parameters needed by the the categoryendpoint server.  After setting any
       * optional parameters, call the {@link InsertCategory#execute()} method to invoke the remote
       * operation. <p> {@link InsertCategory#initialize(com.google.api.client.googleapis.services.Abstr
       * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param content the {@link com.google.api.services.categoryendpoint.model.Category}
       * @since 1.13
       */
      protected InsertCategory(com.google.api.services.categoryendpoint.model.Category content) {
        super(Categoryendpoint.this, "POST", REST_PATH, content, com.google.api.services.categoryendpoint.model.Category.class);
      }

      @Override
      public InsertCategory setAlt(java.lang.String alt) {
        return (InsertCategory) super.setAlt(alt);
      }

      @Override
      public InsertCategory setFields(java.lang.String fields) {
        return (InsertCategory) super.setFields(fields);
      }

      @Override
      public InsertCategory setKey(java.lang.String key) {
        return (InsertCategory) super.setKey(key);
      }

      @Override
      public InsertCategory setOauthToken(java.lang.String oauthToken) {
        return (InsertCategory) super.setOauthToken(oauthToken);
      }

      @Override
      public InsertCategory setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (InsertCategory) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public InsertCategory setQuotaUser(java.lang.String quotaUser) {
        return (InsertCategory) super.setQuotaUser(quotaUser);
      }

      @Override
      public InsertCategory setUserIp(java.lang.String userIp) {
        return (InsertCategory) super.setUserIp(userIp);
      }

      @Override
      public InsertCategory set(String parameterName, Object value) {
        return (InsertCategory) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "categoryEndpoint.listCategory".
     *
     * This request holds the parameters needed by the the categoryendpoint server.  After setting any
     * optional parameters, call the {@link ListCategory#execute()} method to invoke the remote
     * operation.
     *
     * @return the request
     */
    public ListCategory listCategory() throws java.io.IOException {
      ListCategory result = new ListCategory();
      initialize(result);
      return result;
    }

    public class ListCategory extends CategoryendpointRequest<com.google.api.services.categoryendpoint.model.CollectionResponseCategory> {

      private static final String REST_PATH = "category";

      /**
       * Create a request for the method "categoryEndpoint.listCategory".
       *
       * This request holds the parameters needed by the the categoryendpoint server.  After setting any
       * optional parameters, call the {@link ListCategory#execute()} method to invoke the remote
       * operation. <p> {@link
       * ListCategory#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected ListCategory() {
        super(Categoryendpoint.this, "GET", REST_PATH, null, com.google.api.services.categoryendpoint.model.CollectionResponseCategory.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public ListCategory setAlt(java.lang.String alt) {
        return (ListCategory) super.setAlt(alt);
      }

      @Override
      public ListCategory setFields(java.lang.String fields) {
        return (ListCategory) super.setFields(fields);
      }

      @Override
      public ListCategory setKey(java.lang.String key) {
        return (ListCategory) super.setKey(key);
      }

      @Override
      public ListCategory setOauthToken(java.lang.String oauthToken) {
        return (ListCategory) super.setOauthToken(oauthToken);
      }

      @Override
      public ListCategory setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (ListCategory) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public ListCategory setQuotaUser(java.lang.String quotaUser) {
        return (ListCategory) super.setQuotaUser(quotaUser);
      }

      @Override
      public ListCategory setUserIp(java.lang.String userIp) {
        return (ListCategory) super.setUserIp(userIp);
      }

      @Override
      public ListCategory set(String parameterName, Object value) {
        return (ListCategory) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "categoryEndpoint.removeCategory".
     *
     * This request holds the parameters needed by the the categoryendpoint server.  After setting any
     * optional parameters, call the {@link RemoveCategory#execute()} method to invoke the remote
     * operation.
     *
     * @param id
     * @return the request
     */
    public RemoveCategory removeCategory(java.lang.Long id) throws java.io.IOException {
      RemoveCategory result = new RemoveCategory(id);
      initialize(result);
      return result;
    }

    public class RemoveCategory extends CategoryendpointRequest<com.google.api.services.categoryendpoint.model.Category> {

      private static final String REST_PATH = "category/{id}";

      /**
       * Create a request for the method "categoryEndpoint.removeCategory".
       *
       * This request holds the parameters needed by the the categoryendpoint server.  After setting any
       * optional parameters, call the {@link RemoveCategory#execute()} method to invoke the remote
       * operation. <p> {@link RemoveCategory#initialize(com.google.api.client.googleapis.services.Abstr
       * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param id
       * @since 1.13
       */
      protected RemoveCategory(java.lang.Long id) {
        super(Categoryendpoint.this, "DELETE", REST_PATH, null, com.google.api.services.categoryendpoint.model.Category.class);
        this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
      }

      @Override
      public RemoveCategory setAlt(java.lang.String alt) {
        return (RemoveCategory) super.setAlt(alt);
      }

      @Override
      public RemoveCategory setFields(java.lang.String fields) {
        return (RemoveCategory) super.setFields(fields);
      }

      @Override
      public RemoveCategory setKey(java.lang.String key) {
        return (RemoveCategory) super.setKey(key);
      }

      @Override
      public RemoveCategory setOauthToken(java.lang.String oauthToken) {
        return (RemoveCategory) super.setOauthToken(oauthToken);
      }

      @Override
      public RemoveCategory setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (RemoveCategory) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public RemoveCategory setQuotaUser(java.lang.String quotaUser) {
        return (RemoveCategory) super.setQuotaUser(quotaUser);
      }

      @Override
      public RemoveCategory setUserIp(java.lang.String userIp) {
        return (RemoveCategory) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Long id;

      /**

       */
      public java.lang.Long getId() {
        return id;
      }

      public RemoveCategory setId(java.lang.Long id) {
        this.id = id;
        return this;
      }

      @Override
      public RemoveCategory set(String parameterName, Object value) {
        return (RemoveCategory) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "categoryEndpoint.updateCategory".
     *
     * This request holds the parameters needed by the the categoryendpoint server.  After setting any
     * optional parameters, call the {@link UpdateCategory#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link com.google.api.services.categoryendpoint.model.Category}
     * @return the request
     */
    public UpdateCategory updateCategory(com.google.api.services.categoryendpoint.model.Category content) throws java.io.IOException {
      UpdateCategory result = new UpdateCategory(content);
      initialize(result);
      return result;
    }

    public class UpdateCategory extends CategoryendpointRequest<com.google.api.services.categoryendpoint.model.Category> {

      private static final String REST_PATH = "category";

      /**
       * Create a request for the method "categoryEndpoint.updateCategory".
       *
       * This request holds the parameters needed by the the categoryendpoint server.  After setting any
       * optional parameters, call the {@link UpdateCategory#execute()} method to invoke the remote
       * operation. <p> {@link UpdateCategory#initialize(com.google.api.client.googleapis.services.Abstr
       * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param content the {@link com.google.api.services.categoryendpoint.model.Category}
       * @since 1.13
       */
      protected UpdateCategory(com.google.api.services.categoryendpoint.model.Category content) {
        super(Categoryendpoint.this, "PUT", REST_PATH, content, com.google.api.services.categoryendpoint.model.Category.class);
      }

      @Override
      public UpdateCategory setAlt(java.lang.String alt) {
        return (UpdateCategory) super.setAlt(alt);
      }

      @Override
      public UpdateCategory setFields(java.lang.String fields) {
        return (UpdateCategory) super.setFields(fields);
      }

      @Override
      public UpdateCategory setKey(java.lang.String key) {
        return (UpdateCategory) super.setKey(key);
      }

      @Override
      public UpdateCategory setOauthToken(java.lang.String oauthToken) {
        return (UpdateCategory) super.setOauthToken(oauthToken);
      }

      @Override
      public UpdateCategory setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UpdateCategory) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UpdateCategory setQuotaUser(java.lang.String quotaUser) {
        return (UpdateCategory) super.setQuotaUser(quotaUser);
      }

      @Override
      public UpdateCategory setUserIp(java.lang.String userIp) {
        return (UpdateCategory) super.setUserIp(userIp);
      }

      @Override
      public UpdateCategory set(String parameterName, Object value) {
        return (UpdateCategory) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Categoryendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Categoryendpoint}. */
    @Override
    public Categoryendpoint build() {
      return new Categoryendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CategoryendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCategoryendpointRequestInitializer(
        CategoryendpointRequestInitializer categoryendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(categoryendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
