/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-04-29 14:08:19 UTC)
 * on 2013-04-30 at 06:08:53 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.currentuserendpoint.model;

/**
 * Model definition for CurrentUser.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CurrentUser extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isAdmin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isLoggedIn;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String loginUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String logoutUrl;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nickname;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private SystemUser systemUser;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsAdmin() {
    return isAdmin;
  }

  /**
   * @param isAdmin isAdmin or {@code null} for none
   */
  public CurrentUser setIsAdmin(java.lang.Boolean isAdmin) {
    this.isAdmin = isAdmin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsLoggedIn() {
    return isLoggedIn;
  }

  /**
   * @param isLoggedIn isLoggedIn or {@code null} for none
   */
  public CurrentUser setIsLoggedIn(java.lang.Boolean isLoggedIn) {
    this.isLoggedIn = isLoggedIn;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLoginUrl() {
    return loginUrl;
  }

  /**
   * @param loginUrl loginUrl or {@code null} for none
   */
  public CurrentUser setLoginUrl(java.lang.String loginUrl) {
    this.loginUrl = loginUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLogoutUrl() {
    return logoutUrl;
  }

  /**
   * @param logoutUrl logoutUrl or {@code null} for none
   */
  public CurrentUser setLogoutUrl(java.lang.String logoutUrl) {
    this.logoutUrl = logoutUrl;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNickname() {
    return nickname;
  }

  /**
   * @param nickname nickname or {@code null} for none
   */
  public CurrentUser setNickname(java.lang.String nickname) {
    this.nickname = nickname;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public SystemUser getSystemUser() {
    return systemUser;
  }

  /**
   * @param systemUser systemUser or {@code null} for none
   */
  public CurrentUser setSystemUser(SystemUser systemUser) {
    this.systemUser = systemUser;
    return this;
  }

  @Override
  public CurrentUser set(String fieldName, Object value) {
    return (CurrentUser) super.set(fieldName, value);
  }

  @Override
  public CurrentUser clone() {
    return (CurrentUser) super.clone();
  }

}
