/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-04-29 14:08:19 UTC)
 * on 2013-04-30 at 06:08:53 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.currentuserendpoint.model;

/**
 * Model definition for SystemUser.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SystemUser extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isAdmin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nameFirst;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nameLast;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsAdmin() {
    return isAdmin;
  }

  /**
   * @param isAdmin isAdmin or {@code null} for none
   */
  public SystemUser setIsAdmin(java.lang.Boolean isAdmin) {
    this.isAdmin = isAdmin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public SystemUser setKey(java.lang.String key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNameFirst() {
    return nameFirst;
  }

  /**
   * @param nameFirst nameFirst or {@code null} for none
   */
  public SystemUser setNameFirst(java.lang.String nameFirst) {
    this.nameFirst = nameFirst;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNameLast() {
    return nameLast;
  }

  /**
   * @param nameLast nameLast or {@code null} for none
   */
  public SystemUser setNameLast(java.lang.String nameLast) {
    this.nameLast = nameLast;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public SystemUser setUserId(java.lang.String userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public SystemUser set(String fieldName, Object value) {
    return (SystemUser) super.set(fieldName, value);
  }

  @Override
  public SystemUser clone() {
    return (SystemUser) super.clone();
  }

}
