/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-04-29 14:08:19 UTC)
 * on 2013-04-30 at 06:08:53 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.currentuserendpoint;

/**
 * Service definition for Currentuserendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link CurrentuserendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Currentuserendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://project-directory.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "currentuserendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Currentuserendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Currentuserendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the CurrentUserEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Currentuserendpoint currentuserendpoint = new Currentuserendpoint(...);}
   *   {@code Currentuserendpoint.CurrentUserEndpoint.List request = currentuserendpoint.currentUserEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public CurrentUserEndpoint currentUserEndpoint() {
    return new CurrentUserEndpoint();
  }

  /**
   * The "currentUserEndpoint" collection of methods.
   */
  public class CurrentUserEndpoint {

    /**
     * Create a request for the method "currentUserEndpoint.getCurrentUser".
     *
     * This request holds the parameters needed by the the currentuserendpoint server.  After setting
     * any optional parameters, call the {@link GetCurrentUser#execute()} method to invoke the remote
     * operation.
     *
     * @return the request
     */
    public GetCurrentUser getCurrentUser() throws java.io.IOException {
      GetCurrentUser result = new GetCurrentUser();
      initialize(result);
      return result;
    }

    public class GetCurrentUser extends CurrentuserendpointRequest<com.google.api.services.currentuserendpoint.model.CurrentUser> {

      private static final String REST_PATH = "currentuser";

      /**
       * Create a request for the method "currentUserEndpoint.getCurrentUser".
       *
       * This request holds the parameters needed by the the currentuserendpoint server.  After setting
       * any optional parameters, call the {@link GetCurrentUser#execute()} method to invoke the remote
       * operation. <p> {@link GetCurrentUser#initialize(com.google.api.client.googleapis.services.Abstr
       * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @since 1.13
       */
      protected GetCurrentUser() {
        super(Currentuserendpoint.this, "GET", REST_PATH, null, com.google.api.services.currentuserendpoint.model.CurrentUser.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetCurrentUser setAlt(java.lang.String alt) {
        return (GetCurrentUser) super.setAlt(alt);
      }

      @Override
      public GetCurrentUser setFields(java.lang.String fields) {
        return (GetCurrentUser) super.setFields(fields);
      }

      @Override
      public GetCurrentUser setKey(java.lang.String key) {
        return (GetCurrentUser) super.setKey(key);
      }

      @Override
      public GetCurrentUser setOauthToken(java.lang.String oauthToken) {
        return (GetCurrentUser) super.setOauthToken(oauthToken);
      }

      @Override
      public GetCurrentUser setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetCurrentUser) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetCurrentUser setQuotaUser(java.lang.String quotaUser) {
        return (GetCurrentUser) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetCurrentUser setUserIp(java.lang.String userIp) {
        return (GetCurrentUser) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String siteUrl;

      /**

       */
      public java.lang.String getSiteUrl() {
        return siteUrl;
      }

      public GetCurrentUser setSiteUrl(java.lang.String siteUrl) {
        this.siteUrl = siteUrl;
        return this;
      }

      @Override
      public GetCurrentUser set(String parameterName, Object value) {
        return (GetCurrentUser) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Currentuserendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Currentuserendpoint}. */
    @Override
    public Currentuserendpoint build() {
      return new Currentuserendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link CurrentuserendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setCurrentuserendpointRequestInitializer(
        CurrentuserendpointRequestInitializer currentuserendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(currentuserendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
