/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-04-29 14:08:19 UTC)
 * on 2013-04-30 at 06:09:06 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.systemuserendpoint;

/**
 * Service definition for Systemuserendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link SystemuserendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Systemuserendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://project-directory.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "systemuserendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Systemuserendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Systemuserendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the SystemUserEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Systemuserendpoint systemuserendpoint = new Systemuserendpoint(...);}
   *   {@code Systemuserendpoint.SystemUserEndpoint.List request = systemuserendpoint.systemUserEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public SystemUserEndpoint systemUserEndpoint() {
    return new SystemUserEndpoint();
  }

  /**
   * The "systemUserEndpoint" collection of methods.
   */
  public class SystemUserEndpoint {

    /**
     * Create a request for the method "systemUserEndpoint.findByUserId".
     *
     * This request holds the parameters needed by the the systemuserendpoint server.  After setting any
     * optional parameters, call the {@link FindByUserId#execute()} method to invoke the remote
     * operation.
     *
     * @param userId
     * @return the request
     */
    public FindByUserId findByUserId(java.lang.String userId) throws java.io.IOException {
      FindByUserId result = new FindByUserId(userId);
      initialize(result);
      return result;
    }

    public class FindByUserId extends SystemuserendpointRequest<com.google.api.services.systemuserendpoint.model.SystemUser> {

      private static final String REST_PATH = "findByUserId/{userId}";

      /**
       * Create a request for the method "systemUserEndpoint.findByUserId".
       *
       * This request holds the parameters needed by the the systemuserendpoint server.  After setting
       * any optional parameters, call the {@link FindByUserId#execute()} method to invoke the remote
       * operation. <p> {@link
       * FindByUserId#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param userId
       * @since 1.13
       */
      protected FindByUserId(java.lang.String userId) {
        super(Systemuserendpoint.this, "POST", REST_PATH, null, com.google.api.services.systemuserendpoint.model.SystemUser.class);
        this.userId = com.google.api.client.util.Preconditions.checkNotNull(userId, "Required parameter userId must be specified.");
      }

      @Override
      public FindByUserId setAlt(java.lang.String alt) {
        return (FindByUserId) super.setAlt(alt);
      }

      @Override
      public FindByUserId setFields(java.lang.String fields) {
        return (FindByUserId) super.setFields(fields);
      }

      @Override
      public FindByUserId setKey(java.lang.String key) {
        return (FindByUserId) super.setKey(key);
      }

      @Override
      public FindByUserId setOauthToken(java.lang.String oauthToken) {
        return (FindByUserId) super.setOauthToken(oauthToken);
      }

      @Override
      public FindByUserId setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (FindByUserId) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public FindByUserId setQuotaUser(java.lang.String quotaUser) {
        return (FindByUserId) super.setQuotaUser(quotaUser);
      }

      @Override
      public FindByUserId setUserIp(java.lang.String userIp) {
        return (FindByUserId) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String userId;

      /**

       */
      public java.lang.String getUserId() {
        return userId;
      }

      public FindByUserId setUserId(java.lang.String userId) {
        this.userId = userId;
        return this;
      }

      @Override
      public FindByUserId set(String parameterName, Object value) {
        return (FindByUserId) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "systemUserEndpoint.getSystemUser".
     *
     * This request holds the parameters needed by the the systemuserendpoint server.  After setting any
     * optional parameters, call the {@link GetSystemUser#execute()} method to invoke the remote
     * operation.
     *
     * @param key
     * @return the request
     */
    public GetSystemUser getSystemUser(java.lang.String key) throws java.io.IOException {
      GetSystemUser result = new GetSystemUser(key);
      initialize(result);
      return result;
    }

    public class GetSystemUser extends SystemuserendpointRequest<com.google.api.services.systemuserendpoint.model.SystemUser> {

      private static final String REST_PATH = "systemuser/{key}";

      /**
       * Create a request for the method "systemUserEndpoint.getSystemUser".
       *
       * This request holds the parameters needed by the the systemuserendpoint server.  After setting
       * any optional parameters, call the {@link GetSystemUser#execute()} method to invoke the remote
       * operation. <p> {@link GetSystemUser#initialize(com.google.api.client.googleapis.services.Abstra
       * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
       * the constructor. </p>
       *
       * @param key
       * @since 1.13
       */
      protected GetSystemUser(java.lang.String key) {
        super(Systemuserendpoint.this, "GET", REST_PATH, null, com.google.api.services.systemuserendpoint.model.SystemUser.class);
        this.key = com.google.api.client.util.Preconditions.checkNotNull(key, "Required parameter key must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetSystemUser setAlt(java.lang.String alt) {
        return (GetSystemUser) super.setAlt(alt);
      }

      @Override
      public GetSystemUser setFields(java.lang.String fields) {
        return (GetSystemUser) super.setFields(fields);
      }

      @Override
      public GetSystemUser setKey(java.lang.String key) {
        return (GetSystemUser) super.setKey(key);
      }

      @Override
      public GetSystemUser setOauthToken(java.lang.String oauthToken) {
        return (GetSystemUser) super.setOauthToken(oauthToken);
      }

      @Override
      public GetSystemUser setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetSystemUser) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetSystemUser setQuotaUser(java.lang.String quotaUser) {
        return (GetSystemUser) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetSystemUser setUserIp(java.lang.String userIp) {
        return (GetSystemUser) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String key;

      /**

       */
      public java.lang.String getKey() {
        return key;
      }

      public GetSystemUser setKey(java.lang.String key) {
        this.key = key;
        return this;
      }

      @Override
      public GetSystemUser set(String parameterName, Object value) {
        return (GetSystemUser) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "systemUserEndpoint.insertSystemUser".
     *
     * This request holds the parameters needed by the the systemuserendpoint server.  After setting any
     * optional parameters, call the {@link InsertSystemUser#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link com.google.api.services.systemuserendpoint.model.SystemUser}
     * @return the request
     */
    public InsertSystemUser insertSystemUser(com.google.api.services.systemuserendpoint.model.SystemUser content) throws java.io.IOException {
      InsertSystemUser result = new InsertSystemUser(content);
      initialize(result);
      return result;
    }

    public class InsertSystemUser extends SystemuserendpointRequest<com.google.api.services.systemuserendpoint.model.SystemUser> {

      private static final String REST_PATH = "systemuser";

      /**
       * Create a request for the method "systemUserEndpoint.insertSystemUser".
       *
       * This request holds the parameters needed by the the systemuserendpoint server.  After setting
       * any optional parameters, call the {@link InsertSystemUser#execute()} method to invoke the
       * remote operation. <p> {@link InsertSystemUser#initialize(com.google.api.client.googleapis.servi
       * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.google.api.services.systemuserendpoint.model.SystemUser}
       * @since 1.13
       */
      protected InsertSystemUser(com.google.api.services.systemuserendpoint.model.SystemUser content) {
        super(Systemuserendpoint.this, "POST", REST_PATH, content, com.google.api.services.systemuserendpoint.model.SystemUser.class);
      }

      @Override
      public InsertSystemUser setAlt(java.lang.String alt) {
        return (InsertSystemUser) super.setAlt(alt);
      }

      @Override
      public InsertSystemUser setFields(java.lang.String fields) {
        return (InsertSystemUser) super.setFields(fields);
      }

      @Override
      public InsertSystemUser setKey(java.lang.String key) {
        return (InsertSystemUser) super.setKey(key);
      }

      @Override
      public InsertSystemUser setOauthToken(java.lang.String oauthToken) {
        return (InsertSystemUser) super.setOauthToken(oauthToken);
      }

      @Override
      public InsertSystemUser setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (InsertSystemUser) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public InsertSystemUser setQuotaUser(java.lang.String quotaUser) {
        return (InsertSystemUser) super.setQuotaUser(quotaUser);
      }

      @Override
      public InsertSystemUser setUserIp(java.lang.String userIp) {
        return (InsertSystemUser) super.setUserIp(userIp);
      }

      @Override
      public InsertSystemUser set(String parameterName, Object value) {
        return (InsertSystemUser) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "systemUserEndpoint.updateSystemUser".
     *
     * This request holds the parameters needed by the the systemuserendpoint server.  After setting any
     * optional parameters, call the {@link UpdateSystemUser#execute()} method to invoke the remote
     * operation.
     *
     * @param content the {@link com.google.api.services.systemuserendpoint.model.SystemUser}
     * @return the request
     */
    public UpdateSystemUser updateSystemUser(com.google.api.services.systemuserendpoint.model.SystemUser content) throws java.io.IOException {
      UpdateSystemUser result = new UpdateSystemUser(content);
      initialize(result);
      return result;
    }

    public class UpdateSystemUser extends SystemuserendpointRequest<com.google.api.services.systemuserendpoint.model.SystemUser> {

      private static final String REST_PATH = "systemuser";

      /**
       * Create a request for the method "systemUserEndpoint.updateSystemUser".
       *
       * This request holds the parameters needed by the the systemuserendpoint server.  After setting
       * any optional parameters, call the {@link UpdateSystemUser#execute()} method to invoke the
       * remote operation. <p> {@link UpdateSystemUser#initialize(com.google.api.client.googleapis.servi
       * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.google.api.services.systemuserendpoint.model.SystemUser}
       * @since 1.13
       */
      protected UpdateSystemUser(com.google.api.services.systemuserendpoint.model.SystemUser content) {
        super(Systemuserendpoint.this, "PUT", REST_PATH, content, com.google.api.services.systemuserendpoint.model.SystemUser.class);
      }

      @Override
      public UpdateSystemUser setAlt(java.lang.String alt) {
        return (UpdateSystemUser) super.setAlt(alt);
      }

      @Override
      public UpdateSystemUser setFields(java.lang.String fields) {
        return (UpdateSystemUser) super.setFields(fields);
      }

      @Override
      public UpdateSystemUser setKey(java.lang.String key) {
        return (UpdateSystemUser) super.setKey(key);
      }

      @Override
      public UpdateSystemUser setOauthToken(java.lang.String oauthToken) {
        return (UpdateSystemUser) super.setOauthToken(oauthToken);
      }

      @Override
      public UpdateSystemUser setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (UpdateSystemUser) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public UpdateSystemUser setQuotaUser(java.lang.String quotaUser) {
        return (UpdateSystemUser) super.setQuotaUser(quotaUser);
      }

      @Override
      public UpdateSystemUser setUserIp(java.lang.String userIp) {
        return (UpdateSystemUser) super.setUserIp(userIp);
      }

      @Override
      public UpdateSystemUser set(String parameterName, Object value) {
        return (UpdateSystemUser) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Systemuserendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Systemuserendpoint}. */
    @Override
    public Systemuserendpoint build() {
      return new Systemuserendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link SystemuserendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSystemuserendpointRequestInitializer(
        SystemuserendpointRequestInitializer systemuserendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(systemuserendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
